# Improve Bluetooth stability/range for wireless split communication.
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enable stock nice!view display support.
# This keeps the nice!view custom vertical screen.
CONFIG_ZMK_DISPLAY=y

# Blank display when ZMK enters idle.
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y

# Fetch and expose the peripheral half battery level on wireless split builds.
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
